version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ./myapp -c ./etc/
    depends_on:
      - postgres
    networks:
      - nodeart

  postgres:
    container_name: nodeart_db
    image: postgres:14.0
    environment:
      #   environment:
      #     - POSTGRES_USER=${DB_USER}
      #     - POSTGRES_PASSWORD=${DB_PASSWORD}
      #     - POSTGRES_DB=${DB_NAME}
      #     - DATABASE_HOST=${DB_HOST}
      POSTGRES_DB: nodeart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: 127.0.0.1
      PGDATA: /data/postgres
    volumes:
      - ~/docker/nodeart:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nodeart
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations/:/database
    command:
      [ "-path", "/database", "-database",  "postgres://postgres:postgres@nodeart_db:5432/nodeart?sslmode=disable", "up" ]
    networks:
      - nodeart
  pgadmin:
    container_name: pgadminer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/user/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - nodeart
    restart: unless-stopped

networks:
  nodeart:
    driver: bridge

volumes:
  nodeart:
  pgadmin: