// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package nodeart

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT user_id, username, password, email FROM users
WHERE email = $1 AND password = $2 LIMIT 1
`

type GetUserParams struct {
	Email    string
	Password string
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
    username, password, email
) VALUES (
             $1, $2, $3
         )
RETURNING user_id, username, password, email
`

type InsertUserParams struct {
	Username string
	Password string
	Email    string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Username, arg.Password, arg.Email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
	)
	return i, err
}
