app:
  host: "127.0.0.1"
  port: 8080
db:
#  host: "127.0.0.1"
  host: "nodeart_db" # DB host in case of docker-compose
  username: "postgres"
  password: "postgres"
  dbname: "nodeart"
  ssl_mode: "disable"