// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package nodeart_balance

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	BalanceID int32
	UserID    pgtype.Int4
	Balance   pgtype.Float8
	Email     string
}
