// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package nodeart_spin

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Spin struct {
	SpinID      int32
	UserID      pgtype.Int4
	Combination pgtype.Text
	CreatedAt   pgtype.Timestamp
	Email       string
}
